---
version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.9

commands:
  setup_env:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-{{ checksum "requirements/requirements.txt" }}
            - v1-pip
      - run:
          name: Install deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/requirements.txt
            pip install -r requirements/requirements-dev.txt
            pip freeze
      - save_cache:
          key: v1-pip-{{ checksum "requirements/requirements.txt" }}
          paths:
            - ./venv

jobs:
  black:
    executor: python
    steps:
      - setup_env
      - run:
          name: Run Black
          command: |
            . venv/bin/activate
            black --check --diff ccc.py
  rotate_keys:
    executor: python
    parameters:
      rotating_context:
        type: string
        default: default
    steps:
      - setup_env
      - run:
          name: Install circleci cli
          command: curl -fLSs https://circle.ci/cli | VERSION=0.1.11924 sudo bash && alias circleci=/usr/local/bin/circleci
      - run:
          name: Rotate the keys for contexts
          command: |
            . venv/bin/activate
            python ccc.py --context "<< parameters.rotating_context >>"

workflows:
  version: 2
  run:
    jobs:
      - black
      - rotate_keys:
          context:
            - aws_svc_circleci
            - circleci_token
          rotating_context: aws_svc_circleci
          requires:
            - black
          filters:
            branches:
              only: master
      - rotate_keys:
          context:
            - tf-modules
            - circleci_token
          rotating_context: tf-modules
          requires:
            - black
          filters:
            branches:
              only: master
  weekly:
    triggers:
      - schedule:
          cron: "0 3 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - black
      - rotate_keys:
          context:
            - aws_svc_circleci
            - circleci_token
          rotating_context: aws_svc_circleci
          requires:
            - black
      - rotate_keys:
          context:
            - tf-modules
            - circleci_token
          rotating_context: tf-modules
          requires:
            - black
