version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "eana"
    default_labels:
      - "dependencies"
